### PR TITLE
 #160609547 Integrate code coverage using coveralls

### PR DESCRIPTION
**Pull request by samuelbwambale**
### What does this PR do?

Add code coverage to the codebase

#### Description of Task to be completed?

Currently, there is no indicator for test coverage for the code base

This task ensures that test coverage for the repo is obtained and a badge indicating the coverage is displayed in the README file. 

#### How should this be manually tested?

- The badge is visible in the README file
- By clicking on the badge, the details of the test coverage are obtained.

#### Any background context you want to provide?

N/A

#### What are the relevant pivotal tracker stories?

[#160609547](https://www.pivotaltracker.com/story/show/160609547)

### CODE REVIEW

**Comment by samuelbwambale** [comment]
The build is failing because the tests and postgres database branches are not yet merged into the develop branch

**Review by RonKbS — APPROVED** [review]

**Review by mendozabree — APPROVED** [review]

**Comment by samuelbwambale** [comment]
Please note that the coverage is reducing because the tests have not been merged to into develop. Once tests are merged to develop, the coverage will be restored.

**Review by kakaemma — COMMENTED** [review]
Kindly add a newline at the end of coveralls file.

**Comment by samuelbwambale** [comment]
@kaka the new line has been added although it seems not visible here on the UI

**Review by mendozabree — COMMENTED** [review]
Please remove vscode from your .gitignore file

**Comment by samuelbwambale** [comment]
@mendozabree vscode has been removed from .gitignore file.  Please review the changes.

**Comment by lym** [comment]
@samuelbwambale Please resolve the current merge conflicts.

**Comment by samuelbwambale** [comment]
@lym conflict resolved. It was introduced by the merging of travis PR into develop.

**Pull request merged**
