### PR TITLE
#160609538 Tests for User registration/login models and views

### PR DESCRIPTION
**Pull request by samuelbwambale**
### What does this PR do?

Test the UserManager and User models
Test the views for registration and login

#### Description of Task to be completed?

Currently, there are no tests for UserManager and User models. The views for registration and login are not tested as well

This task ensures that the methods in UserManager and User models are tested. Also tests the views to register and login a user.

#### How should this be manually tested?

In the project root, run: coverage run --source=authors/ manage.py test

#### Any background context you want to provide?

N/A

#### What are the relevant pivotal tracker stories?

160609538

### CODE REVIEW

**Review by kakaemma — COMMENTED** [review]
Good work on the tests. However, consider squashing the commits.

**Comment by MuhanguziDavid** [comment]
Noted, we shall work on that

**Review by kakaemma — CHANGES_REQUESTED** [review]
@samuelbwambale, kindly look into the dependencies in the requirements file and use only those that we require.

**Comment by samuelbwambale** [comment]
PR closed to fix multiple commits

**Pull request closed without merging**
