### PR TITLE
feat(documentation-swagger): add documentation to api

### PR DESCRIPTION
**Pull request by mendozabree**
#### What does this PR do?
Creates documentation for the API

#### Description of Task to be completed?
Currently, there is no documentation for the API.

This task creates documentation for the API endpoints that are available and will also reflect all endpoints that will be created after here.

#### How should this be manually tested?
Run ```pip install -r requirements.txt``` in the terminal to install swagger
Run the server and navigate to https://localhost:8000/swagger-docs/
The documentation should appear

#### What are the relevant pivotal tracker stories?
[#160609548](https://www.pivotaltracker.com/story/show/160609548)

#### Any background context you want to add?
N/A

#### Screenshots

image

### CODE REVIEW

**Review by kakaemma — COMMENTED** [review]
Thanks for the work done. Kindly look into removing unused lines, for example, the one in urlpatterns.

**Comment by mendozabree** [comment]
Thanks @kakaemma let me look into that.

**Comment by mendozabree** [comment]
@kakaemma I made the changes.

**Review by RonKbS — COMMENTED** [review]
Nice work Bridget.
Wouldn't it be better to host the documentation on Heroku?

**Review by samuelbwambale — APPROVED** [review]
Good job Bridget. I approve the PR

**Comment by mendozabree** [comment]
@RonKbS the documentation is not hosted anywhere, once the documentation is merged with the Heroku section, it will appear when you run ```<heroku_link>/swagger-docs/```

**Review by MuhanguziDavid — APPROVED** [review]
Great work with the documentation

**Pull request merged**
